# change the build directory to be within react's scope
project_structure:
    build: client/src/artifacts

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# enable output of development artifacts to load with react
dev_deployment_artifacts: true
dotenv: .env

dependencies:
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - OpenZeppelin/openzeppelin-contracts@4.3.2
compiler:
  solc:
    remappings:
      - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2/contracts'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
networks:
  default: hardhat
  kovan:
    verify: True
  rinkeby:
    verify: True
  hardhat:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
